### ISSUE TITLE
Shouldn't assign value of $CUDA_FOUND to $WITH_GPU

### ISSUE THREAD

**Issue by wangkuiyi** [gangliao/bazel.cmake#17]
The following line has a bug

https://github.com/gangliao/bazel.cmake/blob/b2d02605e2b17ae03c8ef2f42f11a347d83f9521/cmake/bazel.cmake#L25-L29

as it assigns the value of ${CUDA_FOUND}, which could be `TRUE` or `FALSE`, to ${WITH_GPU}, which should be either `ON` or `OFF`.

This causes a bug on my macOS with CMake 3.11 that even if CMake found CUDA and set CUDA_FOUND to be TRUE, WITH_GPU will be OFF, because CMake doesn't think TRUE as ON.

**Comment by gangliao** [comment]
We can add a new variable to hold the info for ${CUDA_FOUND}.

```cmake
set(bazel_cuda_found OFF)
if (${CUDA_FOUND})
   set(bazel_cuda_found ON)
endif(${CUDA_FOUND})

option(WITH_GPU     "Compile Source Code with NVIDIA GPU"     ${bazel_cuda_found}) 
```
