### ISSUE TITLE
bazel.cmake requires a very recent version of cmake

### ISSUE THREAD

**Issue by wangkuiyi** [gangliao/bazel.cmake#26]
I just noticed that bazel.cmake doesn't work with cmake 3.5.1 when I used it to build a very simple project. But it could build that project with cmake 3.11.4.

I don't know which exactly the oldest version of cmake is compatible with bazel.cmake, nor the reason it doesn't work with 3.5.1. But I can explain the symptoms I noticed.

## The Setup

I did the verification experiment in a Docker container that runs Ubuntu 16.4 (Xenial):

```bash
docker run --rm -it ubuntu:xenial /bin/bash
```
We need to install the following packages in the container:

```bash
apt-get install -y cmake make gcc git build-essential
```

I created a very simple project in this container. It is basically [this example](https://github.com/gangliao/bazel.cmake/#compile-your-code), except for that I made the hello.cc calls `LOG(INFO) << "Hello World!` instead of `printf`. This would make the target `hello` depends on `glog`.

## Symptoms

If I run `cmake -DWITH_PYTHON=OFF -DWITH_GPU=OFF ..`, where the default version of cmake in Xenial is 3.5.1, it complains:

```
CMake Error at bazel.cmake/cmake/bazel.cmake:67 (list):
  list does not recognize sub-command FILTER
Call Stack (most recent call first):
  bazel.cmake/cmake/bazel.cmake:92 (_build_target)
  bazel.cmake/cmake/bazel.cmake:135 (cmake_library)
  CMakeLists.txt:6 (cc_test)


CMake Error at bazel.cmake/cmake/bazel.cmake:94 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "hello".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.
Call Stack (most recent call first):
  bazel.cmake/cmake/bazel.cmake:135 (cmake_library)
  CMakeLists.txt:6 (cc_test)


CMake Error at bazel.cmake/cmake/bazel.cmake:95 (target_link_libraries):
  Cannot specify link libraries for target "hello" which is not built by this
  project.
Call Stack (most recent call first):
  bazel.cmake/cmake/bazel.cmake:135 (cmake_library)
  CMakeLists.txt:6 (cc_test)
```

Then I downloaded the source code of CMake 3.11.4 and build it. When I run 

```bash
/tmp/cmake-3.11.4/bin/cmake -DWITH_PYTHON=OFF -DWITH_GPU=OFF ..
```

everything goes well.

**Comment by gangliao** [comment]
https://stackoverflow.com/questions/42167432/cmake-list-does-not-recognize-sub-command-filter

`list(FILTER` was introduced in CMake 3.6. I will try to replace it soon.

**Comment by wangkuiyi** [comment]
Thank you! @gangliao 

I'd close https://github.com/wangkuiyi/fluid/pull/25, which installs CMake 3.11.4 for Travis-CI, after your fix.

Also, I am closing https://github.com/gangliao/bazel.cmake/pull/27
